/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboards */
        get: operations["dashboards_api_v1_dashboards_get"];
        put?: never;
        /** Create Dashboard */
        post: operations["create_dashboard_api_v1_dashboards_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboards/{dashboard_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard */
        get: operations["dashboard_api_v1_dashboards__dashboard_id__get"];
        /** Edit Dashboard */
        put: operations["edit_dashboard_api_v1_dashboards__dashboard_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboards/{dashboard_id}/clone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Duplicate Dashboard */
        post: operations["duplicate_dashboard_api_v1_dashboards__dashboard_id__clone_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboards/{dashboard_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish Dashboard */
        post: operations["publish_dashboard_api_v1_dashboards__dashboard_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Datasets */
        get: operations["datasets_api_v1_datasets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Dataset */
        post: operations["upload_dataset_api_v1_datasets_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/chart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dataset Chart */
        post: operations["dataset_chart_api_v1_datasets__dataset_id__chart_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dataset Preview */
        get: operations["dataset_preview_api_v1_datasets__dataset_id__preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dataset Profile */
        get: operations["dataset_profile_api_v1_datasets__dataset_id__profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Structured Dataset Query */
        post: operations["structured_dataset_query_api_v1_datasets__dataset_id__query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/relationships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Relationships */
        post: operations["relationships_api_v1_datasets__dataset_id__relationships_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/relationships/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue Relationships */
        post: operations["queue_relationships_api_v1_datasets__dataset_id__relationships_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/transform": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transform */
        post: operations["transform_api_v1_datasets__dataset_id__transform_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Jobs */
        get: operations["jobs_api_v1_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job */
        get: operations["job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lol/accounts/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Riot Account */
        post: operations["resolve_riot_account_api_v1_lol_accounts_resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lol/benchmarks/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Lolps Benchmark */
        post: operations["upload_lolps_benchmark_api_v1_lol_benchmarks_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lol/dashboards/patch-trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Lol Patch Trend Dashboard
         * @description Create a private dashboard that compares all processed LoL patches.
         */
        post: operations["create_lol_patch_trend_dashboard_api_v1_lol_dashboards_patch_trend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lol/dashboards/starter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Lol Starter Dashboard */
        post: operations["create_lol_starter_dashboard_api_v1_lol_dashboards_starter_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lol/matches/collect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Collect Lol Matches */
        post: operations["collect_lol_matches_api_v1_lol_matches_collect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lol/matches/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Process Lol Matches */
        post: operations["process_lol_matches_api_v1_lol_matches_process_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lol/matches/process-grouped": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Process Lol Matches Grouped
         * @description Process a mixed-patch collection safely rather than applying one item catalog to all games.
         */
        post: operations["process_lol_matches_grouped_api_v1_lol_matches_process_grouped_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lol/static/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync Lol Static */
        post: operations["sync_lol_static_api_v1_lol_static_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics_api_v1_metrics_get"];
        put?: never;
        /** Define Metric */
        post: operations["define_metric_api_v1_metrics_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pipelines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pipelines */
        get: operations["pipelines_api_v1_pipelines_get"];
        put?: never;
        /** Register Pipeline */
        post: operations["register_pipeline_api_v1_pipelines_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pipelines/{pipeline_id}/enabled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Toggle Pipeline */
        post: operations["toggle_pipeline_api_v1_pipelines__pipeline_id__enabled_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pipelines/{pipeline_id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Pipeline */
        post: operations["run_pipeline_api_v1_pipelines__pipeline_id__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_dataset_api_v1_datasets_upload_post */
        Body_upload_dataset_api_v1_datasets_upload_post: {
            /** File */
            file: string;
            /** Name */
            name?: string | null;
            /** Sheet Name */
            sheet_name?: string | null;
        };
        /** Body_upload_lolps_benchmark_api_v1_lol_benchmarks_upload_post */
        Body_upload_lolps_benchmark_api_v1_lol_benchmarks_upload_post: {
            /** File */
            file: string;
            /** Name */
            name?: string | null;
            /** Sheet Name */
            sheet_name?: string | null;
        };
        /** ColumnProfile */
        ColumnProfile: {
            /** Dtype */
            dtype: string;
            /** Maximum */
            maximum?: number | string | null;
            /** Mean */
            mean?: number | null;
            /** Minimum */
            minimum?: number | string | null;
            /** Name */
            name: string;
            /** Null Count */
            null_count: number;
            /** Null Ratio */
            null_ratio: number;
            /** Sample Values */
            sample_values?: unknown[];
            /**
             * Semantic Type
             * @enum {string}
             */
            semantic_type: "numeric" | "categorical" | "datetime" | "text" | "identifier";
            /** Unique Count */
            unique_count: number;
        };
        /** DashboardSummary */
        DashboardSummary: {
            /** Created At */
            created_at: string;
            /** Filters */
            filters: {
                [key: string]: unknown;
            }[];
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Updated At */
            updated_at: string;
            /**
             * Visibility
             * @enum {string}
             */
            visibility: "private" | "published";
            /** Widgets */
            widgets: {
                [key: string]: unknown;
            }[];
        };
        /** DashboardWrite */
        DashboardWrite: {
            /** Filters */
            filters?: {
                [key: string]: unknown;
            }[];
            /** Name */
            name: string;
            /** Widgets */
            widgets?: {
                [key: string]: unknown;
            }[];
        };
        /** DatasetChartRequest */
        DatasetChartRequest: {
            /**
             * Bins
             * @default 20
             */
            bins: number;
            /**
             * Chart Type
             * @enum {string}
             */
            chart_type: "histogram" | "scatter" | "boxplot" | "heatmap";
            /** Filters */
            filters?: components["schemas"]["QueryFilter"][];
            /** Group */
            group?: string | null;
            /**
             * Sample Limit
             * @default 2000
             */
            sample_limit: number;
            /**
             * Seed
             * @default 42
             */
            seed: number;
            /** X */
            x: string;
            /** Y */
            y?: string | null;
        };
        /** DatasetChartResult */
        DatasetChartResult: {
            /** Chart Spec */
            chart_spec: {
                [key: string]: unknown;
            };
            /** Chart Type */
            chart_type: string;
            /** Dataset Id */
            dataset_id: string;
            /** Sample Size */
            sample_size: number;
            /** Version Id */
            version_id: string;
        };
        /** DatasetProfile */
        DatasetProfile: {
            /** Column Count */
            column_count: number;
            /** Columns */
            columns: components["schemas"]["ColumnProfile"][];
            /** Dataset Id */
            dataset_id: string;
            /** Row Count */
            row_count: number;
            /** Version Id */
            version_id: string;
        };
        /** DatasetQuery */
        DatasetQuery: {
            /**
             * Aggregation
             * @default sum
             * @enum {string}
             */
            aggregation: "sum" | "mean" | "count" | "min" | "max";
            /** Dimension */
            dimension?: string | null;
            /** Filters */
            filters?: components["schemas"]["QueryFilter"][];
            /**
             * Limit
             * @default 100
             */
            limit: number;
            /** Measure */
            measure?: string | null;
            /** Series */
            series?: string | null;
        };
        /** DatasetQueryResult */
        DatasetQueryResult: {
            /** Aggregation */
            aggregation: string;
            /** Dataset Id */
            dataset_id: string;
            /** Dimension */
            dimension: string | null;
            /** Measure */
            measure: string | null;
            /** Rows */
            rows: components["schemas"]["DatasetQueryRow"][];
            /** Version Id */
            version_id: string;
        };
        /**
         * DatasetQueryRow
         * @description Stable response shape for aggregated BI queries without changing dict rows.
         */
        DatasetQueryRow: {
            /** Category */
            category?: unknown | null;
            /** Series */
            series?: unknown | null;
            /** Value */
            value: number | null;
        };
        /** DatasetSummary */
        DatasetSummary: {
            /** Column Count */
            column_count?: number | null;
            /** Created At */
            created_at: string;
            /** Current Version Id */
            current_version_id: string | null;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Row Count */
            row_count?: number | null;
            /** Source Type */
            source_type: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobSummary */
        JobSummary: {
            /** Created At */
            created_at: string;
            /** Error */
            error?: string | null;
            /** Id */
            id: string;
            /** Job Type */
            job_type: string;
            /** Progress */
            progress: number;
            /** Result */
            result?: {
                [key: string]: unknown;
            } | null;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "completed" | "failed";
            /** Updated At */
            updated_at: string;
        };
        /** LolStarterDashboardRequest */
        LolStarterDashboardRequest: {
            /** Patch */
            patch: string;
        };
        /** LolStaticSyncRequest */
        LolStaticSyncRequest: {
            /**
             * Bootstrap Samples
             * @default 200
             */
            bootstrap_samples: number;
            /** Version */
            version?: string | null;
        };
        /** MetricSummary */
        MetricSummary: {
            /** Dataset Id */
            dataset_id: string;
            /** Description */
            description: string | null;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Unit */
            unit: string | null;
            /** Value */
            value: number;
        };
        /** MetricWrite */
        MetricWrite: {
            /**
             * Aggregation
             * @enum {string}
             */
            aggregation: "sum" | "mean" | "count" | "min" | "max" | "ratio";
            /** Column */
            column?: string | null;
            /** Dataset Id */
            dataset_id: string;
            /** Denominator */
            denominator?: string | null;
            /** Description */
            description?: string | null;
            /** Name */
            name: string;
            /** Numerator */
            numerator?: string | null;
            /** Unit */
            unit?: string | null;
        };
        /** PipelineRunRequest */
        PipelineRunRequest: {
            /** Idempotency Key */
            idempotency_key: string;
        };
        /** PipelineSummary */
        PipelineSummary: {
            /** Config */
            config?: {
                [key: string]: unknown;
            };
            /** Created At */
            created_at: string;
            /** Dataset Id */
            dataset_id: string;
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Pipeline Type
             * @enum {string}
             */
            pipeline_type: "relationships" | "transform";
            /** Updated At */
            updated_at: string;
        };
        /** PipelineWrite */
        PipelineWrite: {
            /** Config */
            config?: {
                [key: string]: unknown;
            };
            /** Dataset Id */
            dataset_id: string;
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /** Name */
            name: string;
            /**
             * Pipeline Type
             * @enum {string}
             */
            pipeline_type: "relationships" | "transform";
        };
        /** QueryFilter */
        QueryFilter: {
            /** Column */
            column: string;
            /**
             * Operator
             * @default eq
             * @enum {string}
             */
            operator: "eq" | "ne" | "gt" | "gte" | "lt" | "lte" | "in";
            /** Value */
            value: unknown;
        };
        /** RelationshipItem */
        RelationshipItem: {
            /** Chart Spec */
            chart_spec: {
                [key: string]: unknown;
            };
            /** Column */
            column: string;
            /**
             * Direction
             * @enum {string}
             */
            direction: "positive" | "negative" | "none";
            /** Method */
            method: string;
            /** Null Ratio */
            null_ratio: number;
            /** Reason */
            reason: string;
            /** Relation Type */
            relation_type: string;
            /** Sample Size */
            sample_size: number;
            /** Score */
            score: number;
        };
        /** RelationshipRequest */
        RelationshipRequest: {
            /** Analysis Grain */
            analysis_grain?: ("mean" | "latest") | null;
            /**
             * Candidate Limit
             * @default 30
             */
            candidate_limit: number;
            /** Column */
            column: string;
            /** Entity Key */
            entity_key?: string | null;
            /**
             * Minimum Pair Samples
             * @default 100
             */
            minimum_pair_samples: number;
            /**
             * Result Limit
             * @default 5
             */
            result_limit: number;
            /**
             * Sample Limit
             * @default 20000
             */
            sample_limit: number;
            /**
             * Seed
             * @default 42
             */
            seed: number;
            /** Time Column */
            time_column?: string | null;
        };
        /** RelationshipResponse */
        RelationshipResponse: {
            /** Compared Candidates */
            compared_candidates: number;
            /** Dataset Id */
            dataset_id: string;
            /** Items */
            items: components["schemas"]["RelationshipItem"][];
            /** Sampled */
            sampled: boolean;
            /** Selected Column */
            selected_column: string;
            /** Version Id */
            version_id: string;
        };
        /** RiotAccountResolveRequest */
        RiotAccountResolveRequest: {
            /** Game Name */
            game_name: string;
            /** Tag Line */
            tag_line: string;
        };
        /** RiotAccountSummary */
        RiotAccountSummary: {
            /** Game Name */
            game_name: string;
            /** Puuid */
            puuid: string;
            /** Tag Line */
            tag_line: string;
        };
        /** RiotMatchCollectRequest */
        RiotMatchCollectRequest: {
            /**
             * Count
             * @default 10
             */
            count: number;
            /** Puuid */
            puuid: string;
        };
        /** RiotMatchProcessRequest */
        RiotMatchProcessRequest: {
            /** Item Dataset Id */
            item_dataset_id?: string | null;
            /** Match Ids */
            match_ids: string[];
            /**
             * Snapshot Minutes
             * @default [
             *       10,
             *       15,
             *       20
             *     ]
             */
            snapshot_minutes: number[];
        };
        /** TransformRequest */
        TransformRequest: {
            /**
             * Name
             * @default 새 전처리 버전
             */
            name: string;
            /** Steps */
            steps: components["schemas"]["TransformStep"][];
        };
        /** TransformResult */
        TransformResult: {
            /** Column Count */
            column_count: number;
            /** Dataset Id */
            dataset_id: string;
            /** Recipe Id */
            recipe_id: string;
            /** Row Count */
            row_count: number;
            /** Version Id */
            version_id: string;
            /** Version Number */
            version_number: number;
        };
        /** TransformStep */
        TransformStep: {
            /** Config */
            config?: {
                [key: string]: unknown;
            };
            /**
             * Operation
             * @enum {string}
             */
            operation: "select" | "rename" | "cast" | "fill_missing" | "drop_missing" | "drop_duplicates" | "filter" | "calculate" | "aggregate" | "pivot" | "join";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    dashboards_api_v1_dashboards_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"][];
                };
            };
        };
    };
    create_dashboard_api_v1_dashboards_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DashboardWrite"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_api_v1_dashboards__dashboard_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dashboard_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_dashboard_api_v1_dashboards__dashboard_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dashboard_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DashboardWrite"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    duplicate_dashboard_api_v1_dashboards__dashboard_id__clone_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dashboard_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_dashboard_api_v1_dashboards__dashboard_id__publish_post: {
        parameters: {
            query?: {
                published?: boolean;
            };
            header?: never;
            path: {
                dashboard_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    datasets_api_v1_datasets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetSummary"][];
                };
            };
        };
    };
    upload_dataset_api_v1_datasets_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_dataset_api_v1_datasets_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dataset_chart_api_v1_datasets__dataset_id__chart_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DatasetChartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetChartResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dataset_preview_api_v1_datasets__dataset_id__preview_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dataset_profile_api_v1_datasets__dataset_id__profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    structured_dataset_query_api_v1_datasets__dataset_id__query_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DatasetQuery"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetQueryResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    relationships_api_v1_datasets__dataset_id__relationships_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RelationshipRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationshipResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    queue_relationships_api_v1_datasets__dataset_id__relationships_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RelationshipRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transform_api_v1_datasets__dataset_id__transform_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransformRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransformResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    jobs_api_v1_jobs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_riot_account_api_v1_lol_accounts_resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RiotAccountResolveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiotAccountSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_lolps_benchmark_api_v1_lol_benchmarks_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_lolps_benchmark_api_v1_lol_benchmarks_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_lol_patch_trend_dashboard_api_v1_lol_dashboards_patch_trend_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"];
                };
            };
        };
    };
    create_lol_starter_dashboard_api_v1_lol_dashboards_starter_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LolStarterDashboardRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    collect_lol_matches_api_v1_lol_matches_collect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RiotMatchCollectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    process_lol_matches_api_v1_lol_matches_process_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RiotMatchProcessRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    process_lol_matches_grouped_api_v1_lol_matches_process_grouped_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RiotMatchProcessRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_lol_static_api_v1_lol_static_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LolStaticSyncRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_api_v1_metrics_get: {
        parameters: {
            query?: {
                dataset_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    define_metric_api_v1_metrics_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MetricWrite"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pipelines_api_v1_pipelines_get: {
        parameters: {
            query?: {
                enabled?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_pipeline_api_v1_pipelines_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PipelineWrite"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    toggle_pipeline_api_v1_pipelines__pipeline_id__enabled_post: {
        parameters: {
            query: {
                enabled: boolean;
            };
            header?: never;
            path: {
                pipeline_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_pipeline_api_v1_pipelines__pipeline_id__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pipeline_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PipelineRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
